# kubectl apply -f deployment.yaml
# kubectl delete -f deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ksqrt/server:latest
          ports:
            - containerPort: 5000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer
